"""Tests for agenticops.notify.report_formatter module.

Covers: format_report, _to_markdown, _to_html, newsletter rendering,
helper functions (_parse_newsletter_items, _inject_section_ids,
_build_newsletter_toc, _format_contributors).
"""

import pytest

from agenticops.notify.report_formatter import (
    FormattedReport,
    _build_newsletter_toc,
    _format_contributors,
    _inject_section_ids,
    _parse_newsletter_items,
    _to_markdown,
    format_report,
)


# ===========================================================================
# _to_markdown
# ===========================================================================


class TestToMarkdown:
    def test_basic(self):
        result = _to_markdown("# Hello\n\nWorld")
        assert isinstance(result, FormattedReport)
        assert result.format == "markdown"
        assert result.content == b"# Hello\n\nWorld"
        assert result.content_type == "text/markdown; charset=utf-8"
        assert result.extension == ".md"

    def test_unicode(self):
        result = _to_markdown("测试中文内容")
        assert "测试中文内容".encode("utf-8") == result.content

    def test_empty(self):
        result = _to_markdown("")
        assert result.content == b""


# ===========================================================================
# format_report
# ===========================================================================


class TestFormatReport:
    def test_markdown_format(self):
        results = format_report("Test", "# Content", ["markdown"])
        assert len(results) == 1
        assert results[0].format == "markdown"
        assert results[0].extension == ".md"

    def test_html_format(self):
        results = format_report("Test Title", "## Section\n\nParagraph", ["html"])
        assert len(results) == 1
        r = results[0]
        assert r.format == "html"
        assert r.extension == ".html"
        assert r.content_type == "text/html; charset=utf-8"
        html = r.content.decode("utf-8")
        assert "Test Title" in html
        assert "<h2" in html

    def test_html_contains_template_structure(self):
        results = format_report("Report", "Body text", ["html"])
        html = results[0].content.decode("utf-8")
        assert "<!DOCTYPE html>" in html
        assert "Generated by AgenticOps" in html

    def test_multiple_formats(self):
        results = format_report("Multi", "Content", ["markdown", "html"])
        assert len(results) == 2
        formats = {r.format for r in results}
        assert formats == {"markdown", "html"}

    def test_unknown_format_skipped(self):
        results = format_report("X", "Y", ["markdown", "unknown_xyz"])
        assert len(results) == 1
        assert results[0].format == "markdown"

    def test_newsletter_html(self):
        meta = {"report_type": "newsletter", "issue_number": 42, "subtitle": "Weekly"}
        results = format_report("Newsletter", "## Topic\n\nHello", ["html"], report_metadata=meta)
        assert len(results) == 1
        html = results[0].content.decode("utf-8")
        assert "Newsletter" in html
        assert "Issue NO.42" in html
        assert "Weekly" in html

    def test_pdf_skipped_without_weasyprint(self):
        # Weasyprint is unlikely installed in test env
        results = format_report("PDF Test", "content", ["pdf"])
        # Either 0 results (not installed) or 1 (installed)
        if results:
            assert results[0].format == "pdf"

    def test_docx_skipped_without_python_docx(self):
        results = format_report("DOCX Test", "content", ["docx"])
        if results:
            assert results[0].format == "docx"

    def test_case_insensitive_format(self):
        results = format_report("T", "C", ["MARKDOWN", " HTML "])
        assert len(results) == 2

    def test_empty_formats_list(self):
        results = format_report("T", "C", [])
        assert results == []

    def test_report_metadata_default(self):
        # Should not crash when metadata is None
        results = format_report("T", "C", ["html"], report_metadata=None)
        assert len(results) == 1


# ===========================================================================
# Newsletter helpers
# ===========================================================================


class TestParseNewsletterItems:
    def test_contact_badge_chinese(self):
        html = "<p>联系人：张三</p>"
        result = _parse_newsletter_items(html)
        assert "128100" in result  # person emoji code
        assert "张三" in result

    def test_contact_badge_english(self):
        html = "<p>Contact: John<br /></p>"
        result = _parse_newsletter_items(html)
        assert "John" in result
        assert "128100" in result

    def test_confidentiality_badge(self):
        html = "<p>公开范围：内部<br /></p>"
        result = _parse_newsletter_items(html)
        assert "内部" in result
        assert "128274" in result  # lock emoji

    def test_no_match_passthrough(self):
        html = "<p>Normal text</p>"
        result = _parse_newsletter_items(html)
        assert result == html


class TestInjectSectionIds:
    def test_adds_ids(self):
        html = "<h2>First</h2><p>text</p><h2>Second</h2>"
        result = _inject_section_ids(html)
        assert 'id="section-1"' in result
        assert 'id="section-2"' in result

    def test_no_h2_unchanged(self):
        html = "<h3>Not h2</h3>"
        result = _inject_section_ids(html)
        assert result == html

    def test_preserves_existing_attrs(self):
        html = '<h2 class="special">Title</h2>'
        result = _inject_section_ids(html)
        assert 'id="section-1"' in result
        assert "special" in result


class TestBuildNewsletterToc:
    def test_single_section_returns_empty(self):
        html = '<h2 id="section-1">Only One</h2>'
        assert _build_newsletter_toc(html) == ""

    def test_two_sections_builds_toc(self):
        html = '<h2 id="section-1">First</h2><p>x</p><h2 id="section-2">Second</h2>'
        toc = _build_newsletter_toc(html)
        assert "Contents" in toc
        assert "First" in toc
        assert "Second" in toc
        assert "#section-1" in toc
        assert "#section-2" in toc

    def test_strips_inner_tags(self):
        html = '<h2 id="section-1"><strong>Bold</strong></h2><h2 id="section-2">Plain</h2>'
        toc = _build_newsletter_toc(html)
        assert "Bold" in toc
        assert "<strong>" not in toc


class TestFormatContributors:
    def test_empty_list(self):
        assert _format_contributors([]) == ""

    def test_single_contributor(self):
        html = _format_contributors(["Alice"])
        assert "Alice" in html
        assert "Contributors" in html

    def test_multiple_contributors(self):
        html = _format_contributors(["Alice", "Bob", "Charlie"])
        assert "Alice, Bob, Charlie" in html
