"""Property-based tests for SummaryService — summary length constraint.

Feature: chat-session-persistence, Property 7: 摘要长度约束

Uses hypothesis to generate random message sequences, mock the LLM response,
and verify that SummaryService enforces the 500-token max_tokens constraint
in every Bedrock API call.

**Validates: Requirements 5.4**
"""

import json
from unittest.mock import MagicMock, patch

from hypothesis import given, settings as h_settings
from hypothesis import strategies as st

from agenticops.web.summary_service import SummaryService


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Random role for messages
_role_st = st.sampled_from(["user", "assistant"])

# Random text content (1-200 chars)
_text_st = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "P", "Z")),
    min_size=1,
    max_size=200,
)

# A single message dict with simple string content
_simple_message_st = st.fixed_dictionaries({
    "role": _role_st,
    "content": _text_st,
    "_db_id": st.integers(min_value=1, max_value=100000),
})

# A list of messages (1-20 messages)
_messages_st = st.lists(_simple_message_st, min_size=1, max_size=20)

# Random summary text the mock LLM might return (varying lengths)
_summary_text_st = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "P", "Z")),
    min_size=1,
    max_size=2000,
)


def _make_service() -> SummaryService:
    """Create a SummaryService with a mocked Bedrock client."""
    svc = SummaryService.__new__(SummaryService)
    svc.region = "us-east-1"
    svc.model_id = "global.anthropic.claude-haiku-4-5-20251001-v1:0"
    svc._client = MagicMock()
    return svc


def _mock_bedrock_response(mock_client: MagicMock, text: str) -> None:
    """Configure the mock Bedrock client to return the given text."""
    body_bytes = json.dumps({"content": [{"text": text}]}).encode()
    mock_body = MagicMock()
    mock_body.read.return_value = body_bytes
    mock_client.invoke_model.return_value = {"body": mock_body}


def _count_tokens(text: str) -> int:
    """Simple whitespace-based token count approximation."""
    return len(text.split())


# ---------------------------------------------------------------------------
# Property 7: 摘要长度约束
# ---------------------------------------------------------------------------

class TestSummaryLengthConstraint:
    """Property 7: 摘要长度约束

    For any summary generated by SummaryService, the max_tokens parameter
    sent to the Bedrock API shall not exceed 500, ensuring the LLM is
    instructed to respect the token budget.

    Feature: chat-session-persistence, Property 7: 摘要长度约束
    **Validates: Requirements 5.4**
    """

    @given(messages=_messages_st, summary_text=_summary_text_st)
    @h_settings(max_examples=150)
    @patch("agenticops.web.summary_service.get_db_session")
    def test_max_tokens_constraint_in_api_call(
        self, mock_get_db, messages, summary_text
    ):
        """The Bedrock invoke_model call always sets max_tokens <= 500."""
        svc = _make_service()
        _mock_bedrock_response(svc._client, summary_text)

        # Mock DB session
        mock_db = MagicMock()
        mock_get_db.return_value.__enter__ = MagicMock(return_value=mock_db)
        mock_get_db.return_value.__exit__ = MagicMock(return_value=False)

        svc.generate_summary(messages, session_id=1)

        # Verify the API was called
        svc._client.invoke_model.assert_called_once()
        call_kwargs = svc._client.invoke_model.call_args[1]
        body = json.loads(call_kwargs["body"])

        assert "max_tokens" in body, "max_tokens must be present in the API request body"
        assert body["max_tokens"] <= 500, (
            f"max_tokens should be <= 500, got {body['max_tokens']}"
        )

    @given(messages=_messages_st, summary_text=_summary_text_st)
    @h_settings(max_examples=150)
    @patch("agenticops.web.summary_service.get_db_session")
    def test_max_tokens_equals_class_constant(
        self, mock_get_db, messages, summary_text
    ):
        """The max_tokens in the API call matches SummaryService.SUMMARY_MAX_TOKENS."""
        svc = _make_service()
        _mock_bedrock_response(svc._client, summary_text)

        mock_db = MagicMock()
        mock_get_db.return_value.__enter__ = MagicMock(return_value=mock_db)
        mock_get_db.return_value.__exit__ = MagicMock(return_value=False)

        svc.generate_summary(messages, session_id=1)

        call_kwargs = svc._client.invoke_model.call_args[1]
        body = json.loads(call_kwargs["body"])

        assert body["max_tokens"] == SummaryService.SUMMARY_MAX_TOKENS, (
            f"max_tokens should equal SUMMARY_MAX_TOKENS ({SummaryService.SUMMARY_MAX_TOKENS}), "
            f"got {body['max_tokens']}"
        )

    @given(messages=_messages_st, summary_text=_summary_text_st)
    @h_settings(max_examples=150)
    @patch("agenticops.web.summary_service.get_db_session")
    def test_prompt_instructs_token_limit(
        self, mock_get_db, messages, summary_text
    ):
        """The prompt sent to the LLM contains an instruction about the 500 token limit."""
        svc = _make_service()
        _mock_bedrock_response(svc._client, summary_text)

        mock_db = MagicMock()
        mock_get_db.return_value.__enter__ = MagicMock(return_value=mock_db)
        mock_get_db.return_value.__exit__ = MagicMock(return_value=False)

        svc.generate_summary(messages, session_id=1)

        call_kwargs = svc._client.invoke_model.call_args[1]
        body = json.loads(call_kwargs["body"])
        prompt_content = body["messages"][0]["content"]

        assert "500" in prompt_content, (
            "The prompt should mention the 500 token limit to instruct the LLM"
        )

    @given(messages=_messages_st)
    @h_settings(max_examples=150)
    def test_class_constant_is_500(self, messages):
        """SummaryService.SUMMARY_MAX_TOKENS is always 500."""
        assert SummaryService.SUMMARY_MAX_TOKENS == 500, (
            f"SUMMARY_MAX_TOKENS should be 500, got {SummaryService.SUMMARY_MAX_TOKENS}"
        )
