"""Report format converter — Markdown to HTML / PDF / DOCX.

Converts markdown reports to multiple output formats with graceful degradation
when optional dependencies (weasyprint, python-docx) are not installed.

Core dependency: ``markdown`` (pure Python, added to core deps).
Optional: ``weasyprint`` (HTML→PDF), ``python-docx`` (MD→DOCX).
"""

import logging
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Dict, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Availability flags — checked once at import time
# ---------------------------------------------------------------------------

try:
    import markdown as _md

    _HAS_MARKDOWN = True
except ImportError:
    _HAS_MARKDOWN = False

try:
    import weasyprint  # noqa: F401

    _HAS_WEASYPRINT = True
except (ImportError, OSError):
    _HAS_WEASYPRINT = False

try:
    import docx  # noqa: F401

    _HAS_DOCX = True
except ImportError:
    _HAS_DOCX = False


# ---------------------------------------------------------------------------
# Data class
# ---------------------------------------------------------------------------


@dataclass
class FormattedReport:
    """A single formatted output of a report."""

    format: str  # "markdown", "html", "pdf", "docx"
    content: bytes  # Raw file bytes
    content_type: str  # MIME type
    extension: str  # ".md", ".html", ".pdf", ".docx"


# ---------------------------------------------------------------------------
# HTML template (embedded)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
         Oxygen, Ubuntu, Cantarell, sans-serif; max-width: 900px; margin: 0 auto;
         padding: 40px 24px; color: #1e293b; line-height: 1.6; }}
  .header {{ border-bottom: 3px solid #4f46e5; padding-bottom: 16px; margin-bottom: 32px; }}
  .header h1 {{ margin: 0 0 8px; color: #1e293b; font-size: 1.75rem; }}
  .meta {{ color: #64748b; font-size: 0.875rem; }}
  .meta .badge {{ display: inline-block; background: #4f46e5; color: #fff;
                  padding: 2px 10px; border-radius: 4px; font-size: 0.75rem;
                  text-transform: uppercase; letter-spacing: 0.05em; margin-right: 8px; }}
  h2 {{ color: #334155; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }}
  h3 {{ color: #475569; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th, td {{ border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }}
  th {{ background: #f1f5f9; font-weight: 600; }}
  tr:nth-child(even) {{ background: #f8fafc; }}
  code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 3px;
          font-family: 'SF Mono', Consolas, monospace; font-size: 0.9em; }}
  pre {{ background: #1e293b; color: #e2e8f0; padding: 16px; border-radius: 8px;
         overflow-x: auto; }}
  pre code {{ background: none; color: inherit; padding: 0; }}
  blockquote {{ border-left: 4px solid #4f46e5; margin: 16px 0; padding: 8px 16px;
                background: #f8fafc; color: #475569; }}
  .footer {{ margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0;
             color: #94a3b8; font-size: 0.75rem; text-align: center; }}
  @media print {{
    body {{ padding: 0; }}
    pre {{ white-space: pre-wrap; }}
  }}
</style>
</head>
<body>
<div class="header">
  <h1>{title}</h1>
  <div class="meta">
    <span class="badge">{report_type}</span>
    <span>Generated {date}</span>
  </div>
</div>
{body_html}
<div class="footer">Generated by AgenticOps</div>
</body>
</html>
"""

# ---------------------------------------------------------------------------
# Newsletter template (email-safe, table-based layout)
# ---------------------------------------------------------------------------

_NEWSLETTER_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
</head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;">
<tr><td align="center" style="padding:24px 8px;">
<table role="presentation" width="680" cellpadding="0" cellspacing="0" style="max-width:680px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.08);">

  <!-- Header banner -->
  <tr>
    <td style="background:linear-gradient(135deg,#1e293b 0%,#334155 100%);padding:28px 32px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td style="vertical-align:top;">
            <div style="font-size:22px;font-weight:700;color:#ffffff;line-height:1.3;">{title}</div>
            <div style="font-size:13px;color:#94a3b8;margin-top:6px;">{subtitle}</div>
          </td>
          <td style="vertical-align:top;text-align:right;white-space:nowrap;">
            <div style="display:inline-block;background:{classification_bg};color:{classification_fg};font-size:11px;font-weight:700;padding:3px 10px;border-radius:4px;text-transform:uppercase;letter-spacing:0.05em;">{classification}</div>
            <div style="font-size:12px;color:#94a3b8;margin-top:8px;">{issue_label}</div>
            <div style="font-size:12px;color:#94a3b8;margin-top:2px;">{date}</div>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <!-- TOC (injected if >=2 sections) -->
  {toc_html}

  <!-- Body -->
  <tr>
    <td style="padding:24px 32px 32px;font-size:15px;line-height:1.7;color:#334155;">
      {body_html}
    </td>
  </tr>

  <!-- Contributors (conditional) -->
  {contributors_html}

  <!-- Footer -->
  <tr>
    <td style="background:#f8fafc;padding:16px 32px;text-align:center;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0;">
      Generated by AgenticOps &middot; {date}
    </td>
  </tr>

</table>
</td></tr>
</table>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Newsletter helper functions
# ---------------------------------------------------------------------------


def _parse_newsletter_items(body_html: str) -> str:
    """Post-process rendered HTML to convert metadata lines into styled badges.

    Patterns matched (case-insensitive, bilingual):
      - ``联系人：XXX`` / ``Contact: XXX`` → blue contact badge
      - ``公开范围：XXX`` / ``Confidentiality: XXX`` → green scope badge

    Handles both standalone ``<p>`` tags and lines merged by ``nl2br``
    (where consecutive lines share a ``<p>`` separated by ``<br />``).
    """
    # Contact badge — match text before <br> or </p>
    body_html = re.sub(
        r"(?:联系人|Contact)\s*[：:]\s*(.+?)(?=<br\s*/?>|</p>)",
        r'<span style="display:inline-block;background:#dbeafe;color:#1e40af;font-size:12px;padding:2px 10px;border-radius:12px;">&#128100; \1</span>',
        body_html,
        flags=re.IGNORECASE,
    )
    # Confidentiality / scope badge — match text before <br> or </p>
    body_html = re.sub(
        r"(?:公开范围|Confidentiality)\s*[：:]\s*(.+?)(?=<br\s*/?>|</p>)",
        r'<span style="display:inline-block;background:#dcfce7;color:#166534;font-size:12px;padding:2px 10px;border-radius:12px;">&#128274; \1</span>',
        body_html,
        flags=re.IGNORECASE,
    )
    return body_html


def _inject_section_ids(body_html: str) -> str:
    """Add ``id="section-N"`` to ``<h2>`` tags for TOC anchor links."""
    counter = 0

    def _add_id(match: re.Match) -> str:
        nonlocal counter
        counter += 1
        attrs = match.group(1) or ""
        return f'<h2 id="section-{counter}"{" " + attrs if attrs else ""}>'

    return re.sub(r"<h2(?:\s([^>]*))?>", _add_id, body_html)


def _build_newsletter_toc(body_html: str) -> str:
    """Build a numbered TOC box from ``<h2 id="section-N">`` tags.

    Returns empty string if fewer than 2 sections found.
    """
    headings = re.findall(r'<h2 id="section-(\d+)"[^>]*>(.*?)</h2>', body_html, re.DOTALL)
    if len(headings) < 2:
        return ""

    items = []
    for idx, (section_id, text) in enumerate(headings, 1):
        clean = re.sub(r"<[^>]+>", "", text).strip()
        items.append(
            f'<tr><td style="padding:3px 0;font-size:13px;color:#475569;">'
            f'{idx}. <a href="#section-{section_id}" style="color:#4f46e5;text-decoration:none;">{clean}</a>'
            f"</td></tr>"
        )

    return (
        '<tr><td style="padding:16px 32px 0;">'
        '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" '
        'style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:12px 16px;">'
        '<tr><td style="font-size:12px;font-weight:700;color:#64748b;text-transform:uppercase;'
        'letter-spacing:0.05em;padding-bottom:6px;">Contents</td></tr>'
        + "".join(items)
        + "</table></td></tr>"
    )


def _format_contributors(contributors: list) -> str:
    """Render a contributors band. Returns empty string if no contributors."""
    if not contributors:
        return ""
    names = ", ".join(str(c) for c in contributors)
    return (
        '<tr><td style="background:#fefce8;padding:12px 32px;font-size:13px;color:#854d0e;'
        'border-top:1px solid #e2e8f0;">'
        f"<strong>Contributors:</strong> {names}"
        "</td></tr>"
    )


def _to_newsletter_html(
    title: str,
    content: str,
    report_metadata: Dict,
) -> FormattedReport:
    """Render a newsletter-style HTML report.

    ``report_metadata`` may contain:
      - ``issue_number`` (int/str) — e.g. 102
      - ``classification`` (str) — e.g. "Amazon Confidential"
      - ``subtitle`` (str) — e.g. "GenAI Weekly Digest"
      - ``contributors`` (list[str]) — contributor names
    """
    if not _HAS_MARKDOWN:
        return FormattedReport(
            format="html",
            content=f"<html><body><pre>{content}</pre></body></html>".encode("utf-8"),
            content_type="text/html; charset=utf-8",
            extension=".html",
        )

    body_html = _md.markdown(
        content,
        extensions=["tables", "fenced_code", "toc", "nl2br"],
    )

    # Post-process metadata badges
    body_html = _parse_newsletter_items(body_html)

    # Inject section IDs and build TOC
    body_html = _inject_section_ids(body_html)
    toc_html = _build_newsletter_toc(body_html)

    # Inline styles on common tags for email compatibility
    body_html = body_html.replace(
        "<h2", '<h2 style="color:#1e293b;font-size:18px;margin:28px 0 12px;'
        'padding-bottom:6px;border-bottom:2px solid #e2e8f0;"'
    )
    body_html = body_html.replace(
        "<h3", '<h3 style="color:#334155;font-size:15px;margin:20px 0 8px;"'
    )
    body_html = body_html.replace(
        "<table>", '<table style="border-collapse:collapse;width:100%;margin:12px 0;font-size:14px;">'
    )
    body_html = re.sub(
        r"<th(?=[>\s])",
        '<th style="background:#f1f5f9;border:1px solid #cbd5e1;padding:6px 10px;'
        'text-align:left;font-weight:600;font-size:13px;"',
        body_html,
    )
    body_html = re.sub(
        r"<td(?=[>\s])",
        '<td style="border:1px solid #cbd5e1;padding:6px 10px;font-size:13px;"',
        body_html,
    )

    # Metadata from report_metadata
    issue_number = report_metadata.get("issue_number", "")
    classification = report_metadata.get("classification", "")
    subtitle = report_metadata.get("subtitle", "")
    contributors = report_metadata.get("contributors", [])

    issue_label = f"Issue NO.{issue_number}" if issue_number else ""
    classification_bg = "#fbbf24" if classification else "transparent"
    classification_fg = "#78350f" if classification else "transparent"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    contributors_html = _format_contributors(contributors)

    full_html = _NEWSLETTER_HTML_TEMPLATE.format(
        title=title,
        subtitle=subtitle,
        classification=classification,
        classification_bg=classification_bg,
        classification_fg=classification_fg,
        issue_label=issue_label,
        date=now,
        toc_html=toc_html,
        body_html=body_html,
        contributors_html=contributors_html,
    )

    return FormattedReport(
        format="html",
        content=full_html.encode("utf-8"),
        content_type="text/html; charset=utf-8",
        extension=".html",
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def format_report(
    title: str,
    content_markdown: str,
    formats: list[str],
    report_metadata: Optional[dict] = None,
) -> list[FormattedReport]:
    """Convert a markdown report to the requested formats.

    Skips unavailable formats with a warning log instead of raising.

    Args:
        title: Report title.
        content_markdown: Full report content in Markdown.
        formats: List of desired formats, e.g. ``["html", "pdf", "markdown"]``.
        report_metadata: Optional metadata dict (report_type, etc.).

    Returns:
        List of ``FormattedReport`` objects for each successfully generated format.
    """
    meta = report_metadata or {}
    report_type = meta.get("report_type", "report")
    results: list[FormattedReport] = []

    for fmt in formats:
        fmt = fmt.lower().strip()
        try:
            if fmt == "markdown":
                results.append(_to_markdown(content_markdown))
            elif fmt == "html":
                if report_type == "newsletter":
                    results.append(_to_newsletter_html(title, content_markdown, meta))
                else:
                    results.append(_to_html(title, content_markdown, report_type))
            elif fmt == "pdf":
                result = _to_pdf(title, content_markdown, report_type)
                if result:
                    results.append(result)
            elif fmt == "docx":
                result = _to_docx(title, content_markdown, report_type)
                if result:
                    results.append(result)
            else:
                logger.warning("Unknown report format requested: %s", fmt)
        except Exception:
            logger.warning("Failed to generate %s format", fmt, exc_info=True)

    return results


# ---------------------------------------------------------------------------
# Format converters
# ---------------------------------------------------------------------------


def _to_markdown(content: str) -> FormattedReport:
    return FormattedReport(
        format="markdown",
        content=content.encode("utf-8"),
        content_type="text/markdown; charset=utf-8",
        extension=".md",
    )


def _to_html(title: str, content: str, report_type: str) -> FormattedReport:
    if not _HAS_MARKDOWN:
        logger.warning("'markdown' package not installed — HTML generation skipped")
        return FormattedReport(
            format="html",
            content=f"<html><body><pre>{content}</pre></body></html>".encode("utf-8"),
            content_type="text/html; charset=utf-8",
            extension=".html",
        )

    body_html = _md.markdown(
        content,
        extensions=["tables", "fenced_code", "toc", "nl2br"],
    )
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    full_html = _HTML_TEMPLATE.format(
        title=title,
        report_type=report_type,
        date=now,
        body_html=body_html,
    )
    return FormattedReport(
        format="html",
        content=full_html.encode("utf-8"),
        content_type="text/html; charset=utf-8",
        extension=".html",
    )


def _to_pdf(title: str, content: str, report_type: str) -> Optional[FormattedReport]:
    if not _HAS_WEASYPRINT:
        logger.warning("weasyprint not installed — PDF generation skipped (pip install 'agenticops[reports]')")
        return None

    import weasyprint

    html_report = _to_html(title, content, report_type)
    pdf_bytes = weasyprint.HTML(string=html_report.content.decode("utf-8")).write_pdf()
    return FormattedReport(
        format="pdf",
        content=pdf_bytes,
        content_type="application/pdf",
        extension=".pdf",
    )


def _to_docx(title: str, content: str, report_type: str) -> Optional[FormattedReport]:
    if not _HAS_DOCX:
        logger.warning("python-docx not installed — DOCX generation skipped (pip install 'agenticops[reports]')")
        return None

    from docx import Document
    from docx.shared import Pt
    from io import BytesIO

    doc = Document()

    # Title
    doc.add_heading(title, level=0)
    doc.add_paragraph(
        f"Type: {report_type}  |  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    ).style = doc.styles["Subtitle"] if "Subtitle" in [s.name for s in doc.styles] else None
    doc.add_paragraph("")  # spacer

    # Parse markdown into paragraphs — simple heuristic parser
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph("")
            continue

        # Headings
        heading_match = re.match(r"^(#{1,4})\s+(.*)", stripped)
        if heading_match:
            level = len(heading_match.group(1))
            doc.add_heading(heading_match.group(2), level=level)
            continue

        # Bullet points
        if stripped.startswith("- ") or stripped.startswith("* "):
            p = doc.add_paragraph(stripped[2:], style="List Bullet")
            continue

        # Numbered list
        numbered = re.match(r"^\d+\.\s+(.*)", stripped)
        if numbered:
            doc.add_paragraph(numbered.group(1), style="List Number")
            continue

        # Code blocks (```...```)
        if stripped.startswith("```"):
            continue  # skip fences, content lines handled as normal paragraphs

        # Regular paragraph
        p = doc.add_paragraph(stripped)
        for run in p.runs:
            run.font.size = Pt(11)

    buf = BytesIO()
    doc.save(buf)
    return FormattedReport(
        format="docx",
        content=buf.getvalue(),
        content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        extension=".docx",
    )
