"""PredictiveAlert — generate alerts for the existing pipeline.

Spec: PROACTIVE_AGENT_SPEC §4.4
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict

from .pattern_watch import PatternAlert
from .risk_scorer import RiskLevel
from agenticops.utils.timeutils import utc_now

logger = logging.getLogger(__name__)


@dataclass
class ProactiveAlert:
    """Alert generated by proactive prediction, compatible with alert pipeline."""

    source: str = "proactive_agent"
    alert_type: str = ""
    severity: str = "medium"
    title: str = ""
    description: str = ""
    resource_id: str = ""
    timestamp: datetime = field(default_factory=utc_now)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @staticmethod
    def from_pattern(pattern: PatternAlert, risk: RiskLevel) -> "ProactiveAlert":
        """Create a ProactiveAlert from a detected pattern."""
        return ProactiveAlert(
            source="proactive_agent",
            alert_type=f"predictive:{pattern.category}",
            severity=risk.to_severity(),
            title=f"Predicted: {pattern.category} ({pattern.occurrences}x in 7d)",
            description=(
                f"Pattern detected: {pattern.category} has occurred "
                f"{pattern.occurrences} times in the past 7 days. "
                f"Risk score: {pattern.score:.2f}"
            ),
            resource_id=pattern.category,
            metadata={
                "prediction_type": "pattern_recurrence",
                "occurrences": pattern.occurrences,
                "risk_score": pattern.score,
            },
        )

    def to_dict(self) -> dict:
        return {
            "source": self.source,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "title": self.title,
            "description": self.description,
            "resource_id": self.resource_id,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }
