#!/usr/bin/env python3
"""Test: generate and preview HTML reports locally, or publish via SNS.

Usage:
    python scripts/test_html_report_email.py                    # local daily
    python scripts/test_html_report_email.py newsletter         # local newsletter
    python scripts/test_html_report_email.py daily sns          # publish daily via SNS
    python scripts/test_html_report_email.py newsletter sns     # publish newsletter via SNS
"""

import asyncio
import subprocess
import sys
import webbrowser
from pathlib import Path

# Add project to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "report-previews"

SAMPLE_DAILY_REPORT = """\
# Daily Operations Report — 2026-03-05

## Executive Summary

All production systems operating within normal parameters. Two minor
incidents detected and auto-remediated during the reporting period.
Overall SLA compliance: **99.97%**.

## Incident Summary

| # | Severity | Service | Title | Status | MTTR |
|---|----------|---------|-------|--------|------|
| I#127 | High | cartservice | Pod OOM Kill → CrashLoopBackOff | Resolved | 4m 12s |
| I#128 | Medium | frontend | Elevated p99 latency (>500ms) | Resolved | 6m 30s |

## Auto-Remediation Results

### I#127 — cartservice OOM Kill

- **Root Cause**: Memory limit set to 64Mi, actual usage peaked at 112Mi under load
- **Fix Applied**: `kubectl set resources deployment/cartservice -c server --limits=memory=256Mi`
- **Approval Level**: L1 (auto-approved)
- **Verification**: Pod restarted successfully, no further OOM kills in 30min window

### I#128 — Frontend Latency Spike

- **Root Cause**: Upstream `productcatalogservice` returned slow responses due to cold cache
- **Fix Applied**: Restarted `productcatalogservice` pods to clear stale connections
- **Approval Level**: L0 (auto-approved)
- **Verification**: p99 latency returned to <200ms within 3 minutes

## Resource Health

| Resource | Region | Status | CPU | Memory |
|----------|--------|--------|-----|--------|
| EKS `online-boutique` | us-east-1 | Healthy | 42% | 61% |
| RDS `orders-db` | us-east-1 | Healthy | 18% | 45% |
| ElastiCache `sessions` | us-east-1 | Healthy | 22% | 38% |
| Lambda `payment-processor` | us-east-1 | Healthy | — | — |

## Cost Summary (24h)

| Category | Cost | Change |
|----------|------|--------|
| EC2 (EKS nodes) | $12.40 | -3% |
| RDS | $4.80 | — |
| Lambda | $0.12 | +8% |
| S3 | $0.03 | — |
| **Total** | **$17.35** | **-2%** |

## Recommendations

1. **Increase `cartservice` memory limit** to 256Mi permanently (currently patched, needs Helm values update)
2. **Enable HPA** for `productcatalogservice` (min=2, max=5) to handle traffic spikes
3. **Review EKS node capacity** — current utilization at 61% memory, approaching threshold

---

*Generated by AgenticOps — Auto-Fix Pipeline v1.0*
"""

SAMPLE_NEWSLETTER_REPORT = """\
# GenAI Weekly Digest

## LLM Fine-Tuning Best Practices

Large-scale fine-tuning experiments on domain-specific corpora show consistent
improvements when using LoRA adapters with rank=16 on attention layers.

联系人：Alice Wang (AWS Applied AI)
公开范围：Amazon Confidential

### Key Findings

| Model | Base Accuracy | Fine-Tuned | Improvement |
|-------|--------------|------------|-------------|
| Claude 4.6 Sonnet | 82.3% | 91.7% | +9.4% |
| Llama 3.1 70B | 78.1% | 86.4% | +8.3% |

- LoRA rank=16 outperforms rank=8 by ~2% on domain tasks
- Training on 10K curated examples sufficient for most use cases
- Evaluation should include both automated metrics and human review

## RAG Pipeline Optimization / RAG 管线优化

Hybrid retrieval (sparse BM25 + dense embeddings) consistently outperforms
single-strategy approaches across all benchmark datasets.

联系人：Bob Chen (Search Science)
公开范围：Internal Only

### Architecture Overview

```
Query → [BM25 + Vector Search] → Reciprocal Rank Fusion → Re-ranker → LLM
```

- **Latency**: p50=120ms, p99=340ms (target: <500ms)
- **Recall@10**: 94.2% (up from 87.1% with dense-only)
- **Production deployment**: 3 regions, 12M documents indexed

## Cost Optimization for Inference Workloads

Spot instances with checkpointing reduce inference costs by 60-70% for
batch workloads with flexible completion deadlines.

Contact: Charlie Liu (Cloud Economics)
Confidentiality: Amazon Confidential

### Cost Comparison (Monthly, 1000 req/day)

| Strategy | Monthly Cost | Savings |
|----------|-------------|---------|
| On-Demand GPU | $4,200 | — |
| Reserved (1yr) | $2,940 | 30% |
| Spot + Checkpoint | $1,260 | 70% |

## Agent Framework Evaluation

Evaluation of multi-agent orchestration frameworks for production SRE
automation workloads.

联系人：David Park (SRE Automation)
公开范围：Amazon Confidential

- **Strands SDK**: Best for single-provider (AWS Bedrock), native tool registry
- **LangGraph**: Best for complex DAG workflows, strong observability
- **CrewAI**: Best for role-based agent teams, easiest to prototype
"""

NEWSLETTER_METADATA = {
    "issue_number": 102,
    "classification": "Amazon Confidential",
    "subtitle": "GenAI Weekly Digest — Applied AI & Infrastructure",
    "contributors": [
        "Alice Wang", "Bob Chen", "Charlie Liu", "David Park",
    ],
}


def _get_report_params(report_type: str) -> dict:
    """Return title, summary, content, metadata for each report type."""
    if report_type == "newsletter":
        return {
            "report_id": 1000,
            "title": "GenAI Weekly Digest — Issue NO.102",
            "summary": "4 articles: LLM fine-tuning, RAG optimization, cost savings, agent frameworks.",
            "content_markdown": SAMPLE_NEWSLETTER_REPORT,
            "report_type": "newsletter",
            "report_metadata": NEWSLETTER_METADATA,
        }
    return {
        "report_id": 999,
        "title": "Daily Operations Report — 2026-03-05",
        "summary": "All systems healthy. 2 incidents auto-remediated. SLA: 99.97%.",
        "content_markdown": SAMPLE_DAILY_REPORT,
        "report_type": "daily",
        "report_metadata": {},
    }


def run_local(report_type: str) -> None:
    """Generate HTML locally, save to data/report-previews/, open in browser."""
    from agenticops.notify.report_formatter import format_report

    params = _get_report_params(report_type)
    meta = dict(params["report_metadata"])
    meta["report_type"] = params["report_type"]

    results = format_report(
        title=params["title"],
        content_markdown=params["content_markdown"],
        formats=["html", "markdown"],
        report_metadata=meta,
    )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for fr in results:
        out_path = OUTPUT_DIR / f"{report_type}-preview{fr.extension}"
        out_path.write_bytes(fr.content)
        print(f"  {fr.format}: {out_path}  ({len(fr.content)} bytes)")

    html_path = OUTPUT_DIR / f"{report_type}-preview.html"
    if html_path.exists():
        print(f"\nOpening in browser: {html_path}")
        webbrowser.open(html_path.as_uri())


async def run_sns(report_type: str) -> None:
    """Publish report via SNS to email subscribers."""
    from agenticops.notify.im_config import load_channels
    from agenticops.notify.notifier import SNSReportNotifier

    channels = load_channels()
    sns_channels = [c for c in channels if c.channel_type == "sns-report" and c.is_enabled]

    if not sns_channels:
        print("ERROR: No enabled sns-report channel found in channels.yaml")
        sys.exit(1)

    ch = sns_channels[0]
    print(f"Using channel: {ch.name}")
    print(f"  topic_arn: {ch.config.get('topic_arn')}")
    print(f"  s3_bucket: {ch.config.get('s3_bucket')}")
    print(f"  formats:   {ch.config.get('formats', ['html', 'markdown'])}")
    print()

    notifier = SNSReportNotifier(ch.config)
    params = _get_report_params(report_type)

    print(f"Publishing {report_type.upper()} report via SNS...")
    result = await notifier.send_report(**params)

    print(f"\nResult:")
    print(f"  Formats: {result.get('formats')}")
    print(f"  URLs:    {result.get('urls')}")
    print(f"  SNS MessageId: {result.get('message_id')}")

    if result.get("message_id"):
        print(f"\n{report_type.upper()} report published to SNS.")
    else:
        print("\nWARNING: No message ID returned — check logs.")


async def main():
    args = sys.argv[1:]
    report_type = args[0] if args else "daily"
    backend = args[1] if len(args) > 1 else "local"

    if report_type not in ("daily", "newsletter"):
        print(f"Unknown report type: {report_type}. Use 'daily' or 'newsletter'.")
        sys.exit(1)

    print(f"Report: {report_type}  |  Backend: {backend}\n")

    if backend == "sns":
        await run_sns(report_type)
    else:
        run_local(report_type)


if __name__ == "__main__":
    asyncio.run(main())
